
@hostname = localhost
@port = 5001
@host = {{hostname}}:{{port}}
@vehicle_id = 1

### Get all
GET http://{{host}}/api/vehicles/

### Create
POST http://{{host}}/api/vehicles?user=4
Content-Type: application/json

{
  "type":"EV",
  "make":"Hyundai",
  "model":"Kona",
  "commissioned": true,
  "license_plate": "BC-214"
}

### Create
POST http://{{host}}/api/users/
Content-Type: application/json

{
  "name": "Sampsa Tervo",
  "username": "sateri23"
}

### Get single
GET http://{{host}}/api/vehicles/{{vehicle_id}}

### Modify
PUT http://{{host}}/api/vehicles/{{vehicle_id}}

### Delete vehicle entry
DELETE http://{{host}}/api/vehicles/{{vehicle_id}}

