
@hostname = [::1]
@port = 5001
@host = {{hostname}}:{{port}}
@ObjectID = 63f4832566635f9ede6682e1


### Get all
GET http://{{host}}/api/vehicles/

### Create
POST http://{{host}}/api/vehicles/
Content-Type: application/json

{
    "type":"EV",
    "make":"Hyundai",
    "model":"Kona"
}

### Create
POST http://{{host}}/api/vehicles/
Content-Type: application/json

{
    "type":"EV",
    "make":"Tesla",
    "model":"3"
}

### Create
POST http://{{host}}/api/vehicles/
Content-Type: application/json

{
  "type": "Passenger car",
  "make": "Honda",
  "model": "Transit"
}

### Create
POST http://{{host}}/api/vehicles/
Content-Type: application/json

{
  "type": "Van",
  "make": "Ford",
  "model": "Transit"
}

### Create
POST http://{{host}}/api/vehicles/
Content-Type: application/json

{
  "type": "Pick-up",
  "make": "Dodge",
  "model": "Ram"
}

### Get single
GET http://{{host}}/api/vehicles/{{ObjectID}}

### Modify
PUT http://{{host}}/api/vehicles/{{ObjectID}}
Content-Type: application/json

{
    "type":"Van",
    "make":"Tesla",
    "model":"3"
}

### Delete (won't work without query string "login=johndoe")
DELETE http://{{host}}/api/vehicles/{{ObjectID}}

### Delete with user information
DELETE http://{{host}}/api/vehicles/{{ObjectID}}?login=johndoe
