

PUT http://localhost:5001/api/albums/3 HTTP/1.1
Content-Type: application/json

{
        "artist": "Test3",
        "title": "Test222",
        "year": 2021,
        "genre": "Rock",
        "tracks": 11
}